### ISSUE TITLE
Lowercase the first character of first word of the commit message and remove last period

### ISSUE THREAD

**Issue by xshapira** [lanesket/painy#3]
The first character of `Add` needs to be lowercase. And the last period `.` needs to be removed.

![Screen Shot](https://user-images.githubusercontent.com/48856190/228914517-979e241e-3825-4f22-a1cd-df850f7d859c.JPG)

So it will read, `add number 6 to the list in notes file`

**Comment by lanesket** [comment]
@xshapira It's your own preference, but it's not a panacea. In future versions, there will be an option to change the model's prompt so that you can add your own wishes to the model how it should generate the commit message. For now, you can clone a repository and install a package from it by modifying the prompt in `painy/comment.py`
